/**
 * Swagger Sentient Light
 * This is the API description of Interoberlin Sentient Light
 *
 * OpenAPI spec version: 1.0.0
 * Contact: florian.schwanz@interoberlin.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BluetoothCharacteristicApi {

    protected basePath = 'http://sentient.interoberlin.de/v1';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * @summary Disables value notification of a bluetooth characteristic
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public disableValueNotification(uuid: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.disableValueNotificationWithHttpInfo(uuid, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Enables value notification of a bluetooth characteristic
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public enableValueNotification(uuid: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.enableValueNotificationWithHttpInfo(uuid, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Get bluetooth characteristic by uuid
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public getBluetoothGattCharacteristic(uuid: string, extraHttpRequestParams?: any): Observable<models.BluetoothGattCharacteristic> {
        return this.getBluetoothGattCharacteristicWithHttpInfo(uuid, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Returns bluetooth service's characteristics
     * @param uuid The uuid of the bluetooth service. 
     */
    public getCharacteristics(uuid: string, extraHttpRequestParams?: any): Observable<models.BluetoothGattCharacteristic> {
        return this.getCharacteristicsWithHttpInfo(uuid, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Reads a bluetooth characteristic's value
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public readValue(uuid: string, extraHttpRequestParams?: any): Observable<models.BluetoothGattCharacteristic> {
        return this.readValueWithHttpInfo(uuid, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary Writes a value to a given characteristic
     * @param uuid The uuid of the bluetooth characteristic. 
     * @param value Value to be written in characteristic
     */
    public writeValue(uuid: string, value: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.writeValueWithHttpInfo(uuid, value, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * Disables value notification of a bluetooth characteristic
     * 
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public disableValueNotificationWithHttpInfo(uuid: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/bluetoothCharacteristic/${uuid}/disableValueNotification'
                    .replace('${' + 'uuid' + '}', String(uuid));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'uuid' is not null or undefined
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling disableValueNotification.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Enables value notification of a bluetooth characteristic
     * 
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public enableValueNotificationWithHttpInfo(uuid: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/bluetoothCharacteristic/${uuid}/enableValueNotification'
                    .replace('${' + 'uuid' + '}', String(uuid));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'uuid' is not null or undefined
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling enableValueNotification.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Get bluetooth characteristic by uuid
     * 
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public getBluetoothGattCharacteristicWithHttpInfo(uuid: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/bluetoothCharacteristic/${uuid}/'
                    .replace('${' + 'uuid' + '}', String(uuid));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'uuid' is not null or undefined
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling getBluetoothGattCharacteristic.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Returns bluetooth service&#39;s characteristics
     * 
     * @param uuid The uuid of the bluetooth service. 
     */
    public getCharacteristicsWithHttpInfo(uuid: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/bluetoothService/${uuid}/characteristics'
                    .replace('${' + 'uuid' + '}', String(uuid));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'uuid' is not null or undefined
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling getCharacteristics.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Reads a bluetooth characteristic&#39;s value
     * 
     * @param uuid The uuid of the bluetooth characteristic. 
     */
    public readValueWithHttpInfo(uuid: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/bluetoothCharacteristic/${uuid}/readValue'
                    .replace('${' + 'uuid' + '}', String(uuid));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'uuid' is not null or undefined
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling readValue.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * Writes a value to a given characteristic
     * 
     * @param uuid The uuid of the bluetooth characteristic. 
     * @param value Value to be written in characteristic
     */
    public writeValueWithHttpInfo(uuid: string, value: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/bluetoothCharacteristic/${uuid}/writeValue'
                    .replace('${' + 'uuid' + '}', String(uuid));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        let formParams = new URLSearchParams();

        // verify required parameter 'uuid' is not null or undefined
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling writeValue.');
        }
        // verify required parameter 'value' is not null or undefined
        if (value === null || value === undefined) {
            throw new Error('Required parameter value was null or undefined when calling writeValue.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        headers.set('Content-Type', 'application/x-www-form-urlencoded');

        if (value !== undefined) {
            formParams.set('value', <any>value);
        }

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: formParams.toString(),
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
