/**
 * Swagger Sentient Light
 * This is the API description of Interoberlin Sentient Light
 *
 * OpenAPI spec version: 1.0.0
 * Contact: florian.schwanz@interoberlin.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface BluetoothGattCharacteristic {
    uuid?: string;

    value?: string;

    notifying?: boolean;

    characteristics?: Array<string>;

}
